# fly.toml app configuration file generated for part11-full-stack-open-pokedex on 2024-03-02T20:03:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part11-full-stack-open-pokedex'
primary_region = 'ams'

[build]

[deploy]
  strategy = "canary"

[env]
  PORT = "5000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
