name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: '20'
          - name: Install dependencies 
            run: npm install  
          - name: Check style
            run: npm run eslint
          - name: build
            run: npm run build
          - name: test
            run: npm run test
          - name: e2e tests
            uses: cypress-io/github-action@v5
            with:
              command: npm run test:e2e
              start: npm run start-prod
              wait-on: http://localhost:5000
          - uses: superfly/flyctl-actions/setup-flyctl@master
          - name: deploy
            if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') || (github.event_name == 'pull_request' && !contains(github.event.pull_request.title + github.event.pull_request.body, '#skip')) }}
            run: flyctl deploy --remote-only
            env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    tag_release:
        needs: [simple_deployment_pipeline]
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') || (github.event_name == 'pull_request' && !contains(github.event.pull_request.title + github.event.pull_request.body, '#skip')) }}
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - name: version number and tag
              uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
              env:
                DEFAULT_BUMP: patch
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                WITH_V: true
